# AlertManager configuration for TipTap production alerts

global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: '${SMTP_HOST}:587'
  smtp_from: 'alerts@tiptap.com'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

  # The API URL to use for Slack notifications.
  slack_api_url: '${SLACK_API_URL}'

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters.
route:
  # The labels by which incoming alerts are grouped together.
  group_by: ['alertname', 'cluster', 'service']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 2m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 4h

  # A default receiver
  receiver: default-notifications

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
  # Critical alerts go to PagerDuty and Slack immediately
  - match:
      severity: critical
    receiver: critical-alerts
    group_wait: 10s
    repeat_interval: 1h
    continue: true

  # Payment-related alerts
  - match:
      team: payments
    receiver: payments-team
    group_wait: 30s
    repeat_interval: 2h
    routes:
    - match:
        severity: critical
      receiver: payments-critical
      group_wait: 10s
      repeat_interval: 30m

  # Security alerts
  - match:
      team: security
    receiver: security-team
    group_wait: 15s
    repeat_interval: 1h
    routes:
    - match:
        alertname: FraudScoreSpike
      receiver: security-fraud
      group_wait: 5s
      repeat_interval: 30m

  # Infrastructure alerts
  - match:
      team: infrastructure
    receiver: infrastructure-team
    group_wait: 1m
    repeat_interval: 3h

  # Business/Product alerts
  - match:
      team: product
    receiver: product-team
    group_wait: 5m
    repeat_interval: 6h

  # Finance alerts
  - match:
      team: finance
    receiver: finance-team
    group_wait: 30s
    repeat_interval: 1h
    routes:
    - match:
        alertname: LowBalanceAlert
      receiver: finance-critical
      group_wait: 10s
      repeat_interval: 15m

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

- source_match:
    alertname: 'ServiceDown'
  target_match_re:
    alertname: '.*'
  equal: ['instance']

receivers:
- name: 'default-notifications'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_GENERAL}'
    channel: '#alerts'
    title: 'TipTap Alert'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      *Details:*
      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
      {{ end }}
      {{ end }}

- name: 'critical-alerts'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_SERVICE_KEY}'
    description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'
    details:
      firing: '{{ .Alerts.Firing | len }}'
      resolved: '{{ .Alerts.Resolved | len }}'
      group_labels: '{{ .GroupLabels.SortedPairs }}'
    custom_details:
      runbook_url: '{{ .CommonAnnotations.runbook_url }}'

  slack_configs:
  - api_url: '${SLACK_WEBHOOK_CRITICAL}'
    channel: '#critical-alerts'
    title: '🚨 CRITICAL ALERT 🚨'
    color: 'danger'
    text: |
      {{ range .Alerts }}
      *CRITICAL:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|Click here>{{ end }}
      *Labels:*
      {{ range .Labels.SortedPairs }}  • {{ .Name }}: `{{ .Value }}`
      {{ end }}
      {{ end }}

  email_configs:
  - to: ['oncall@tiptap.com', 'cto@tiptap.com']
    subject: '🚨 TipTap Critical Alert: {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL ALERT: {{ .GroupLabels.alertname }}

      {{ range .Alerts }}
      Summary: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ if .Annotations.runbook_url }}Runbook: {{ .Annotations.runbook_url }}{{ end }}

      Labels:
      {{ range .Labels.SortedPairs }}  - {{ .Name }}: {{ .Value }}
      {{ end }}
      {{ end }}

- name: 'payments-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_PAYMENTS}'
    channel: '#payments-alerts'
    title: '💳 Payment System Alert'
    color: 'warning'
    text: |
      {{ range .Alerts }}
      *Alert:* {{ .Annotations.summary }}
      *Impact:* Payment processing may be affected
      {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|Payment Issues Guide>{{ end }}
      {{ end }}

- name: 'payments-critical'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_PAYMENTS_KEY}'
    description: 'Critical Payment Issue: {{ .CommonAnnotations.summary }}'

  slack_configs:
  - api_url: '${SLACK_WEBHOOK_PAYMENTS}'
    channel: '#payments-critical'
    title: '🚨 CRITICAL PAYMENT ALERT 🚨'
    color: 'danger'
    text: |
      {{ range .Alerts }}
      *CRITICAL PAYMENT ISSUE*
      {{ .Annotations.summary }}

      This is impacting customer payments and revenue!
      {{ if .Annotations.runbook_url }}
      *Immediate Action Required:* <{{ .Annotations.runbook_url }}|Follow Runbook>
      {{ end }}
      {{ end }}

  email_configs:
  - to: ['payments-team@tiptap.com', 'finance@tiptap.com']
    subject: '🚨 Critical Payment Alert'

- name: 'security-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_SECURITY}'
    channel: '#security-alerts'
    title: '🛡️ Security Alert'
    color: 'danger'
    text: |
      {{ range .Alerts }}
      *Security Issue:* {{ .Annotations.summary }}
      *Description:* {{ .Annotations.description }}
      {{ if .Annotations.runbook_url }}*Security Playbook:* <{{ .Annotations.runbook_url }}|Investigate Now>{{ end }}
      {{ end }}

  email_configs:
  - to: ['security@tiptap.com']
    subject: '🛡️ TipTap Security Alert'

- name: 'security-fraud'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_SECURITY_KEY}'
    description: 'Fraud Detection Alert: {{ .CommonAnnotations.summary }}'

  slack_configs:
  - api_url: '${SLACK_WEBHOOK_SECURITY}'
    channel: '#fraud-alerts'
    title: '🚨 FRAUD ALERT 🚨'
    color: 'danger'
    text: |
      *POTENTIAL FRAUD DETECTED*
      {{ range .Alerts }}
      {{ .Annotations.summary }}

      Immediate investigation required!
      {{ end }}

- name: 'infrastructure-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_INFRASTRUCTURE}'
    channel: '#infrastructure-alerts'
    title: '🔧 Infrastructure Alert'
    color: 'warning'
    text: |
      {{ range .Alerts }}
      *Infrastructure Issue:* {{ .Annotations.summary }}
      *Impact:* {{ .Annotations.description }}
      {{ if .Annotations.runbook_url }}*Runbook:* <{{ .Annotations.runbook_url }}|Fix Guide>{{ end }}
      {{ end }}

  email_configs:
  - to: ['devops@tiptap.com']
    subject: '🔧 Infrastructure Alert'

- name: 'product-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_PRODUCT}'
    channel: '#product-alerts'
    title: '📊 Product Metrics Alert'
    text: |
      {{ range .Alerts }}
      *Product Metric:* {{ .Annotations.summary }}
      *Details:* {{ .Annotations.description }}
      {{ end }}

- name: 'finance-team'
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_FINANCE}'
    channel: '#finance-alerts'
    title: '💰 Finance Alert'
    color: 'warning'
    text: |
      {{ range .Alerts }}
      *Financial Alert:* {{ .Annotations.summary }}
      *Action Required:* {{ .Annotations.description }}
      {{ end }}

  email_configs:
  - to: ['finance@tiptap.com', 'cfo@tiptap.com']
    subject: '💰 TipTap Finance Alert'

- name: 'finance-critical'
  pagerduty_configs:
  - service_key: '${PAGERDUTY_FINANCE_KEY}'
    description: 'Critical Finance Alert: {{ .CommonAnnotations.summary }}'

  slack_configs:
  - api_url: '${SLACK_WEBHOOK_FINANCE}'
    channel: '#finance-critical'
    title: '🚨 CRITICAL FINANCE ALERT 🚨'
    color: 'danger'
    text: |
      *CRITICAL FINANCIAL ISSUE*
      {{ range .Alerts }}
      {{ .Annotations.summary }}

      Immediate attention required - this affects business operations!
      {{ end }}

  email_configs:
  - to: ['finance@tiptap.com', 'ceo@tiptap.com', 'cfo@tiptap.com']
    subject: '🚨 CRITICAL: TipTap Finance Alert'

  # SMS for critical financial alerts
  webhook_configs:
  - url: '${SMS_WEBHOOK_URL}'
    send_resolved: false
    http_config:
      basic_auth:
        username: '${SMS_API_USER}'
        password: '${SMS_API_PASS}'
    title: 'TipTap Critical Alert'
    text: |
      {{ range .Alerts }}
      CRITICAL: {{ .Annotations.summary }}
      {{ end }}

# Silence configuration
silence:
  # Enable web UI for managing silences
  web_listen_address: ":9093"

  # Default silence duration
  default_duration: "1h"

# Template files for custom formatting
template_files:
  - '/etc/alertmanager/templates/slack.tmpl'
  - '/etc/alertmanager/templates/email.tmpl'